"""Enumerations for the Acrobat Sign REST API v6 values used by this client.

Acrobat Sign adds enum values over time, so every model field typed with one
of these enums is declared as ``Enum | str``: a known value parses into the
enum member, an unknown one is kept as the raw string instead of failing.
Each enum subclasses ``str`` so members compare equal to their wire values.
"""

from __future__ import annotations

from enum import Enum


class AgreementStatus(str, Enum):
    """``AgreementInfo.status`` / ``UserAgreement.status`` values (v6)."""

    OUT_FOR_SIGNATURE = "OUT_FOR_SIGNATURE"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    OUT_FOR_ACCEPTANCE = "OUT_FOR_ACCEPTANCE"
    OUT_FOR_FORM_FILLING = "OUT_FOR_FORM_FILLING"
    OUT_FOR_APPROVAL = "OUT_FOR_APPROVAL"
    AUTHORING = "AUTHORING"
    CANCELLED = "CANCELLED"
    SIGNED = "SIGNED"
    APPROVED = "APPROVED"
    DELIVERED = "DELIVERED"
    ACCEPTED = "ACCEPTED"
    FORM_FILLED = "FORM_FILLED"
    EXPIRED = "EXPIRED"
    ARCHIVED = "ARCHIVED"
    PREFILL = "PREFILL"
    WIDGET_WAITING_FOR_VERIFICATION = "WIDGET_WAITING_FOR_VERIFICATION"
    DRAFT = "DRAFT"
    DOCUMENTS_NOT_YET_PROCESSED = "DOCUMENTS_NOT_YET_PROCESSED"
    WAITING_FOR_FAXIN = "WAITING_FOR_FAXIN"
    WAITING_FOR_VERIFICATION = "WAITING_FOR_VERIFICATION"
    WAITING_FOR_NOTARIZATION = "WAITING_FOR_NOTARIZATION"


class AgreementCreateState(str, Enum):
    """The ``state`` an agreement may be created in via ``POST /agreements``."""

    IN_PROCESS = "IN_PROCESS"
    DRAFT = "DRAFT"
    AUTHORING = "AUTHORING"


class ParticipantRole(str, Enum):
    """``ParticipantSetInfo.role`` values (v6)."""

    SIGNER = "SIGNER"
    APPROVER = "APPROVER"
    ACCEPTOR = "ACCEPTOR"
    CERTIFIED_RECIPIENT = "CERTIFIED_RECIPIENT"
    FORM_FILLER = "FORM_FILLER"
    DELEGATE_TO_SIGNER = "DELEGATE_TO_SIGNER"
    DELEGATE_TO_APPROVER = "DELEGATE_TO_APPROVER"
    DELEGATE_TO_ACCEPTOR = "DELEGATE_TO_ACCEPTOR"
    DELEGATE_TO_CERTIFIED_RECIPIENT = "DELEGATE_TO_CERTIFIED_RECIPIENT"
    DELEGATE_TO_FORM_FILLER = "DELEGATE_TO_FORM_FILLER"
    NOTARY_SIGNER = "NOTARY_SIGNER"
    ELECTRONIC_SEALER = "ELECTRONIC_SEALER"


class ParticipantSetStatus(str, Enum):
    """``DetailedParticipantSetInfo.status`` values seen on ``/members``."""

    WAITING_FOR_MY_SIGNATURE = "WAITING_FOR_MY_SIGNATURE"
    WAITING_FOR_MY_APPROVAL = "WAITING_FOR_MY_APPROVAL"
    WAITING_FOR_MY_DELEGATION = "WAITING_FOR_MY_DELEGATION"
    WAITING_FOR_MY_ACKNOWLEDGEMENT = "WAITING_FOR_MY_ACKNOWLEDGEMENT"
    WAITING_FOR_MY_ACCEPTANCE = "WAITING_FOR_MY_ACCEPTANCE"
    WAITING_FOR_MY_FORM_FILLING = "WAITING_FOR_MY_FORM_FILLING"
    WAITING_FOR_OTHERS = "WAITING_FOR_OTHERS"
    WAITING_FOR_AUTHORING = "WAITING_FOR_AUTHORING"
    NOT_YET_VISIBLE = "NOT_YET_VISIBLE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    DECLINED = "DECLINED"
    REPLACED = "REPLACED"


class SignatureType(str, Enum):
    """``AgreementInfo.signatureType`` values."""

    ESIGN = "ESIGN"
    WRITTEN = "WRITTEN"


class AgreementEventType(str, Enum):
    """A subset of ``AgreementEvent.type`` values from ``/agreements/{id}/events``.

    The full list is long and grows; unknown types parse as plain strings.
    """

    CREATED = "CREATED"
    ACTION_REQUESTED = "ACTION_REQUESTED"
    EMAIL_VIEWED = "EMAIL_VIEWED"
    EMAIL_BOUNCED = "EMAIL_BOUNCED"
    ESIGNED = "ESIGNED"
    SIGNED = "SIGNED"
    APPROVED = "APPROVED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    DELEGATED = "DELEGATED"
    REPLACED_SIGNER = "REPLACED_SIGNER"
    REJECTED = "REJECTED"
    RECALLED = "RECALLED"
    EXPIRED = "EXPIRED"
    AUTO_CANCELLED_CONVERSION_PROBLEM = "AUTO_CANCELLED_CONVERSION_PROBLEM"
    SHARED = "SHARED"
    MODIFIED = "MODIFIED"
    REMINDER_SENT = "REMINDER_SENT"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"


class WebhookScope(str, Enum):
    """``WebhookInfo.scope`` values."""

    ACCOUNT = "ACCOUNT"
    GROUP = "GROUP"
    USER = "USER"
    RESOURCE = "RESOURCE"


class WebhookState(str, Enum):
    """``WebhookInfo.state`` values."""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class WebhookResourceType(str, Enum):
    """``WebhookInfo.resourceType`` values (only AGREEMENT is in v0.1 scope)."""

    AGREEMENT = "AGREEMENT"
    WIDGET = "WIDGET"
    MEGASIGN = "MEGASIGN"
    LIBRARY_DOCUMENT = "LIBRARY_DOCUMENT"


class WebhookEvent(str, Enum):
    """Agreement webhook subscription / notification event names."""

    AGREEMENT_ALL = "AGREEMENT_ALL"
    AGREEMENT_CREATED = "AGREEMENT_CREATED"
    AGREEMENT_ACTION_REQUESTED = "AGREEMENT_ACTION_REQUESTED"
    AGREEMENT_ACTION_COMPLETED = "AGREEMENT_ACTION_COMPLETED"
    AGREEMENT_WORKFLOW_COMPLETED = "AGREEMENT_WORKFLOW_COMPLETED"
    AGREEMENT_EXPIRED = "AGREEMENT_EXPIRED"
    AGREEMENT_EXPIRATION_UPDATED = "AGREEMENT_EXPIRATION_UPDATED"
    AGREEMENT_RECALLED = "AGREEMENT_RECALLED"
    AGREEMENT_REJECTED = "AGREEMENT_REJECTED"
    AGREEMENT_ACTION_DELEGATED = "AGREEMENT_ACTION_DELEGATED"
    AGREEMENT_ACTION_REPLACED_SIGNER = "AGREEMENT_ACTION_REPLACED_SIGNER"
    AGREEMENT_MODIFIED = "AGREEMENT_MODIFIED"
    AGREEMENT_USER_ACK_AGREEMENT_MODIFIED = "AGREEMENT_USER_ACK_AGREEMENT_MODIFIED"
    AGREEMENT_SHARED = "AGREEMENT_SHARED"
    AGREEMENT_UNSHARED = "AGREEMENT_UNSHARED"
    AGREEMENT_EMAIL_VIEWED = "AGREEMENT_EMAIL_VIEWED"
    AGREEMENT_EMAIL_BOUNCED = "AGREEMENT_EMAIL_BOUNCED"
    AGREEMENT_AUTO_CANCELLED_CONVERSION_PROBLEM = (
        "AGREEMENT_AUTO_CANCELLED_CONVERSION_PROBLEM"
    )
    AGREEMENT_OFFLINE_SYNC = "AGREEMENT_OFFLINE_SYNC"
    AGREEMENT_DOCUMENTS_DELETED = "AGREEMENT_DOCUMENTS_DELETED"
    AGREEMENT_READY_TO_NOTARIZE = "AGREEMENT_READY_TO_NOTARIZE"
    AGREEMENT_READY_TO_VAULT = "AGREEMENT_READY_TO_VAULT"
    AGREEMENT_VAULTED = "AGREEMENT_VAULTED"
    AGREEMENT_KBA_AUTHENTICATED = "AGREEMENT_KBA_AUTHENTICATED"
    AGREEMENT_WEB_IDENTITY_AUTHENTICATED = "AGREEMENT_WEB_IDENTITY_AUTHENTICATED"
    AGREEMENT_REMINDER_SENT = "AGREEMENT_REMINDER_SENT"
    AGREEMENT_REMINDER_INITIATED = "AGREEMENT_REMINDER_INITIATED"
